version: "3.8"

services:
    redis:
        image: redis:6.0-alpine
        ports:
            - "6379:6379"

    scheduler:
        image: job-scheduler:${IMAGE_TAG}
        command: make scheduler
        depends_on: 
            - redis
        environment:
            APP_DATABASE_URL: redis://redis
            APP_BROKER_URL: redis://redis

    runner:
        image: job-scheduler:${IMAGE_TAG}
        command: make runner
        depends_on: 
            - redis
            - dummy-endpoint
        environment:
            APP_DATABASE_URL: redis://redis
            APP_BROKER_URL: redis://redis

    api:
        image: job-scheduler:${IMAGE_TAG}
        ports:
            - "8000:8000"
        command: make api
        depends_on: 
            - redis
        environment: 
            APP_API_HOST: 0.0.0.0
            APP_API_RELOAD: "False"
            APP_DATABASE_URL: redis://redis

    dummy-endpoint:
        image: job-scheduler:${IMAGE_TAG}
        command: make dummy
        ports:
            - "8080"
        environment: 
            APP_DUMMY_HOST: "0.0.0.0"
            APP_DUMMY_PORT: "8080"
            APP_DUMMY_RELOAD: "False"
            APP_DUMMY_SLEEP: 0.2