version: "3.8"

services:
    redis:
        image: redis:6.0-alpine
        ports:
            - "6379"

    scheduler:
        image: job-scheduler:${IMAGE_TAG}
        command: make scheduler
        depends_on: 
            - redis
        volumes:
            - ./job_scheduler:/app/job_scheduler:ro
        environment:
            APP_DATABASE_URL: redis://redis
            APP_BROKER_URL: redis://redis
            APP_DEV_MODE: 1

    runner:
        image: job-scheduler:${IMAGE_TAG}
        command: make runner
        depends_on: 
            - redis
            - dummy-endpoint
        volumes:
            - ./job_scheduler:/app/job_scheduler:ro
        environment:
            APP_DATABASE_URL: redis://redis
            APP_BROKER_URL: redis://redis
            APP_DEV_MODE: 1

    api:
        image: job-scheduler:${IMAGE_TAG}
        ports:
            - "8000:8000"
        command: make api
        depends_on: 
            - redis
        volumes:
            - ./job_scheduler:/app/job_scheduler:ro
        environment: 
            APP_API_HOST: 0.0.0.0
            APP_API_PORT: 8000
            APP_DATABASE_URL: redis://redis
            APP_DEV_MODE: 1


    dummy-endpoint:
        image: job-scheduler:${IMAGE_TAG}
        command: make dummy
        ports:
            - "8080"
        volumes:
            - ./job_scheduler:/app/job_scheduler:ro
        environment: 
            APP_DUMMY_HOST: 0.0.0.0
            APP_DUMMY_PORT: 8080
            APP_DEV_MODE: 1
            APP_DUMMY_SLEEP: 0.2