version: "3.8"

services:
    redis:
        image: redis:6.2-alpine
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"

    scheduler:
        image: job-scheduler:${IMAGE_TAG}-dev
        build:
            context: ./
            target: dev
        command: just scheduler
        depends_on: 
            - redis
            - rabbitmq
        volumes:
            - ./job_scheduler:/app/job_scheduler:ro
        environment:
            APP_DATABASE_URL: redis://redis
            APP_BROKER_URL: amqp://rabbitmq
            APP_CACHE_URL: redis://redis
            APP_BROKER_USERNAME: guest
            APP_BROKER_PASSWORD: guest
            APP_DEV_MODE: 1

    runner:
        image: job-scheduler:${IMAGE_TAG}-dev
        build:
            context: ./
            target: dev
        command: just runner
        depends_on: 
            - rabbitmq
            - redis
            - dummy-endpoint
        volumes:
            - ./job_scheduler:/app/job_scheduler:ro
        environment:
            APP_DATABASE_URL: redis://redis
            APP_BROKER_URL: amqp://rabbitmq
            APP_BROKER_USERNAME: guest
            APP_BROKER_PASSWORD: guest
            APP_DEV_MODE: 1

    api:
        image: job-scheduler:${IMAGE_TAG}-dev
        build:
            context: ./
            target: dev
        ports:
            - "8000:8000"
        command: just api
        depends_on: 
            - redis
        volumes:
            - ./job_scheduler:/app/job_scheduler:ro
        environment: 
            APP_API_HOST: 0.0.0.0
            APP_API_PORT: 8000
            APP_DATABASE_URL: redis://redis
            APP_DEV_MODE: 1

    dummy-endpoint:
        image: job-scheduler:${IMAGE_TAG}-dev
        build:
            context: ./
            target: dev
        command: just dummy
        ports:
            - "8080"
        volumes:
            - ./job_scheduler:/app/job_scheduler:ro
        environment: 
            APP_DUMMY_HOST: 0.0.0.0
            APP_DUMMY_PORT: 8080
            APP_DUMMY_SLEEP: 0.2
            APP_DEV_MODE: 1
