POST http://localhost:8000/schedule/

{
    "name": "Test Name",
    "description": "Test Description",
    "schedule": "* * * * *",
    "job": {
        "callback_url": "http://dummy-endpoint:8080",
        "http_method": "post",
        "payload": {
            "name": "Test User"
        }
    }
}

###

GET  http://localhost:8000/schedule/901f5dc5-42e4-479c-a9db-37e52bf2ba56


###
PUT  http://localhost:8000/schedule/0f180ca3-1d30-4e56-8ebd-365daa4f5c67

{
    "name": "updated",
    "description": "updated schedule",
    "schedule": "* * * * *",
    "active": false
}


###
DELETE http://localhost:8000/schedule/0f180ca3-1d30-4e56-8ebd-365daa4f5c67