name: Job Scheduler CI
on:
  pull_request:
    branches:
      - master
  push:

jobs:
  ci:
    name: Run full test pipeline
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set target python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Install just
        uses: extractions/setup-just@v1

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install AWS CDK
        run: sudo npm install -g aws-cdk

      - name: Install the project and dependencies
        run: poetry install

      - name: Ensure lint steps pass
        run: just lint

      - name: Ensure CDK is passing
        run: just cfn

      - name: Run tests
        run: just test
