name: Job Scheduler CI
on:
  pull_request:
    branches:
      - master
  push:

jobs:
  ci:
    name: Run full test pipeline
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.0-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
    
      - name: Set target python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install the project and dependencies
        run: poetry install

      - name: Run tests
        run: make test